language: ruby

sudo: false
cache: bundler

branches:
  only:
    - master

rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.3
  - jruby-9.2.8.0

script:
  - bundle exec rake test

gemfile:
  - gemfiles/Gemfile-rspec-3.7.x
  - gemfiles/Gemfile-rspec-3.8.x
